
	</div><!--/content-->
	<footer>
      <p>A project by <a href="http://raphaelbastide.com/">Raphaël Bastide</a> — <a href="https://github.com/raphaelbastide/usemodify">Source code</a> on GitHub</p>
	</footer>

  <script src="<?php echo $config->urls->templates?>scripts/jquery.js"></script>
  <script src="<?php echo $config->urls->templates?>scripts/cookies.js"></script>
  <script src="<?php echo $config->urls->templates?>scripts/main.js"></script>
</body>
</html>
